- name: vim install
  hosts: all
  tasks:
    - name: install httpd
      yum: name=httpd state=latest
     # yum: name=httpd state=absent
    - name: enable httpd
      service: name=httpd state=started
